{% set version = "1.2.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-laminr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/laminr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/laminr/laminr_{{ version }}.tar.gz
  sha256: e81578a44dd7ceb46eb9fcfaa5a0a3d4d2d8ec6f49a0f8eacecd52f3ae93b7f4

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.1.0
    - r-callr
    - r-cli
    - r-lifecycle
    - r-pkgload
    - r-purrr
    - r-r.utils
    - r-r6
    - r-reticulate >=1.41.0
    - r-rlang
    - r-sessioninfo
  run:
    - r-base
    - r-callr
    - r-cli
    - r-lifecycle
    - r-pkgload
    - r-purrr
    - r-r.utils
    - r-r6
    - r-reticulate >=1.41.0
    - r-rlang
    - r-sessioninfo

test:
  commands:
    - $R -e "library('laminr')"           # [not win]
    - "\"%R%\" -e \"library('laminr')\""  # [win]

about:
  home: https://cran.r-project.org/package=laminr
  summary: 'R client for LaminDB'
  description: |
    laminr is a R client for LaminDB. LaminDB is an open-source data
    framework to enable learning at scale in computational biology. It lets
    you track data transformations, curate datasets, manage metadata, and
    query a built-in database for biological entities & data structures.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE-2.0.txt
  doc_url: https://laminr.lamin.ai/
  dev_url: https://github.com/laminlabs/laminr

extra:
  recipe-maintainers:
    - conda-forge/r
    - ap--
    - zethson
    - sunnyosun

# Package: laminr
# Title: Client for 'LaminDB'
# Version: 1.2.0
# Authors@R: c(
#     person("Robrecht", "Cannoodt", , "robrecht@lamin.ai", role = c("aut", "cre"),
#            comment = c(ORCID = "0000-0003-3641-729X")),
#     person("Luke", "Zappia", , "luke@data-intuitive.com", role = "aut",
#            comment = c(ORCID = "0000-0001-7744-8565")),
#     person("Data Intuitive", , , "info@data-intuitive.com", role = "aut"),
#     person("Lamin Labs", , , "open-source@lamin.ai", role = c("aut", "cph"))
#   )
# Description: Interact with 'LaminDB'. 'LaminDB' is an open-source data
#     framework for biology. This package allows you to query and download
#     data from 'LaminDB' instances.
# License: Apache License (>= 2)
# URL: https://laminr.lamin.ai, https://github.com/laminlabs/laminr
# BugReports: https://github.com/laminlabs/laminr/issues
# Depends: R (>= 4.1.0)
# Imports: callr, cli, lifecycle, pkgload, purrr, R.utils, R6, reticulate
#         (>= 1.41.0), rlang, sessioninfo, utils, withr
# Suggests: anndata, arrow, jsonlite, knitr, magick, readr, rmarkdown,
#         rstudioapi, rsvg, testthat (>= 3.0.0), yaml
# VignetteBuilder: knitr
# Config/Needs/website: rmarkdown, Seurat
# Config/testthat/edition: 3
# Encoding: UTF-8
# RoxygenNote: 7.3.3
# NeedsCompilation: no
# Packaged: 2025-10-09 09:37:11 UTC; sunnysun
# Author: Robrecht Cannoodt [aut, cre] (ORCID:
#     <https://orcid.org/0000-0003-3641-729X>),
#   Luke Zappia [aut] (ORCID: <https://orcid.org/0000-0001-7744-8565>),
#   Data Intuitive [aut],
#   Lamin Labs [aut, cph]
# Maintainer: Robrecht Cannoodt <robrecht@lamin.ai>
# Repository: CRAN
# Date/Publication: 2025-10-09 09:50:10 UTC
